// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// NewTodo defines model for NewTodo.
type NewTodo struct {
	Title string `json:"title"`
}

// Todo defines model for Todo.
type Todo struct {
	Done  bool   `json:"done"`
	Id    int64  `json:"id"`
	Title string `json:"title"`
}

// TodoList defines model for TodoList.
type TodoList = []Todo

// PostTodosJSONRequestBody defines body for PostTodos for application/json ContentType.
type PostTodosJSONRequestBody = NewTodo

// PutTodosIdJSONRequestBody defines body for PutTodosId for application/json ContentType.
type PutTodosIdJSONRequestBody = Todo
