version: '3.8'

services:
  # MySQLサービス
  mysql:
    image: mysql:8.0
    container_name: todoapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapi_db
      MYSQL_USER: todoapi_user
      MYSQL_PASSWORD: todoapi_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todoapi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Golangアプリケーションサービス
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapi-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: todoapi_user
      DB_PASSWORD: todoapi_pass
      DB_NAME: todoapi_db
    networks:
      - todoapi-network

volumes:
  mysql_data:
    driver: local

networks:
  todoapi-network:
    driver: bridge