
services:
  mysql:
    image: mysql:8.0
    container_name: db_practice_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: practice_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_practice_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_practice_app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: practice_db
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - db_practice_network

volumes:
  mysql_data:

networks:
  db_practice_network:
    driver: bridge